### ISSUE TITLE
Perses 1.4 crashes on paste operator in C programs

### ISSUE THREAD

**Issue by rkchang** [uw-pluverse/perses#25]
When Perses encounters a token paste operator in a C program it throws an exception and then hangs. Probably the same issue as #23

```
❯ java -jar perses_deploy.jar --version
perses version 1.4
Git Version: dbae2214e13816df8370448e85185c0645785409
Git Branch: master
Git Status: Clean
Built on 2020-11-11T11:54:41.933756-05:00[America/Toronto]
```

perses_test.c:
```
#define TEST(x) x##1

int main(void) {
    return TEST(0);
}
```

perses_test.sh
```
#!/bin/bash

gcc perses_test.c -o perses_test
```

Error:
```
❯ java -jar perses_deploy.jar --test-script perses_test.sh --input-file perses_test.c
[18:44:23] [INFO   ] Tree Building: Start building spar-tree from input file SourceFile{file=/home/rkchang/dev/omp/perses_test.c, lang=org.perses.grammar.c.LanguageC@1bce4f0a}
[18:44:23] [INFO   ] Tree Building: Step 1: Antlr parsing.
Exception in thread "main" org.perses.grammar.AntlrFailureException: Error in parsing file: <in memory>
Details: recognizer: org.perses.grammar.c.PnfCLexer@1c9f0a20
offendingSymbol: null
line: 1
column: 17
msg: token recognition error at: '##'

Caused by: LexerNoViableAltException('#')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:152)
	at org.antlr.v4.runtime.BufferedTokenStream.setup(BufferedTokenStream.java:254)
	at org.antlr.v4.runtime.BufferedTokenStream.lazyInit(BufferedTokenStream.java:249)
	at org.antlr.v4.runtime.CommonTokenStream.LT(CommonTokenStream.java:92)
	at org.antlr.v4.runtime.Parser.enterRule(Parser.java:628)
	at org.perses.grammar.c.PnfCParser.translationUnit(PnfCParser.java:9661)
	at org.perses.grammar.c.PnfCParserFacade.startParsing(PnfCParserFacade.java:42)
	at org.perses.grammar.c.PnfCParserFacade.startParsing(PnfCParserFacade.java:24)
	at org.perses.grammar.AbstractDefaultParserFacade.parseReader(AbstractDefaultParserFacade.java:189)
	at org.perses.grammar.AbstractDefaultParserFacade.parseReader(AbstractDefaultParserFacade.java:136)
	at org.perses.grammar.AbstractParserFacade.parseString(AbstractParserFacade.java:108)
	at org.perses.grammar.AbstractParserFacade.parseString(AbstractParserFacade.java:98)
	at org.perses.reduction.ReductionDriver.createSparTree(ReductionDriver.kt:437)
	at org.perses.reduction.ReductionDriver.<init>(ReductionDriver.kt:77)
	at org.perses.Main.run(Main.java:91)
	at org.perses.Main.main(Main.java:47)
```

**Comment by chengniansun** [comment]
This is because preprocessor macros are not a part of the c language.
